defaults:
     - config_schema
     - _self_

params:
    dis_lr: 1e-4
    gen_lr: 1e-4
    patch_size: 96
    batch_size: 8  # {8, 32}
    num_workers: 2  # {1, 12}
    num_epochs: 2
    w0: 1e-0  # LPIPS weight
    w1: 1e-0  # SSIM weight
    w2: 1e-3  # Adversarial loss weight
    
    unet:
        num_filters: 64
        use_residual: True
        use_batch_norm: False
        scale_factor: 4

paths:
    project_dir: ${hydra:runtime.cwd}

    data_dir: "${paths.project_dir}/data"
    train_dir: "${paths.data_dir}/train"
    val_dir: "${paths.data_dir}/val"
    test_dir: "${paths.data_dir}/test"
    train_original_frames_dir: "${paths.train_dir}/original_frames"
    train_encoded_frames_dir: "${paths.train_dir}/encoded_frames"
    val_original_frames_dir: "${paths.val_dir}/original_frames"
    val_encoded_frames_dir: "${paths.val_dir}/encoded_frames"
    test_original_frames_dir: "${paths.test_dir}/original_frames"
    test_encoded_frames_dir: "${paths.test_dir}/encoded_frames"
    
    artifacts_dir: "${paths.project_dir}/artifacts"
